import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;

class IconManager {
  // Icônes Material pour Android
  static const Map<String, IconData> _materialIcons = {
    'home': Icons.home,
    'menu': Icons.menu,
    'search': Icons.search,
    'add': Icons.add,
    'delete': Icons.delete,
    'edit': Icons.edit,
    'notifications': Icons.notifications,
    'profile': Icons.person,
    'logout': Icons.logout,
    'email': Icons.email_outlined,
    'phone': Icons.phone_outlined,
    'password': Icons.lock_outline,
    'visibility_on': Icons.visibility,
    'visibility_off': Icons.visibility_off,
    'check': Icons.check_circle,
    'check_outline': Icons.check_circle_outline,
    'camera': Icons.camera_alt,
    'photo_library': Icons.photo_library,
    'cloud_upload': Icons.cloud_upload,
    'upload_file': Icons.upload_file,
    'location': Icons.location_on_outlined,
    'arrow_forward': Icons.arrow_forward,
    'arrow_back': Icons.arrow_back,
    'message': Icons.message,
    'download': Icons.download,
    'share': Icons.share,
    'refresh': Icons.refresh,
    'cart': Icons.shopping_cart,
    'restaurant': Icons.restaurant_menu,
    'delivery': Icons.delivery_dining,
    'history': Icons.history,
    'payment': Icons.payment,
    'info': Icons.info_outline,
    'success': Icons.check_circle_outline,
    'warning': Icons.warning_amber_outlined,
    'error': Icons.error_outline,
    'close': Icons.close,
    'filter': Icons.tune,
    'clock': Icons.watch_later_outlined,
    'star': Icons.star,
    'home_outlined': Icons.home_outlined,
    'wallet': Icons.account_balance_wallet_outlined,
    // Icônes supplémentaires utilisées dans l'application
    'delete_outline': Icons.delete_outline,
    'remove': Icons.remove,
    'notifications_outlined': Icons.notifications_none_outlined,
    'done_all': Icons.done_all,
    'more_vert': Icons.more_vert,
    'shopping_bag_outlined': Icons.shopping_bag_outlined,
    'local_offer_outlined': Icons.local_offer_outlined,
    'payment_outlined': Icons.payment_outlined,
    'mark_as_unread': Icons.mark_as_unread,
    'done': Icons.done,
    'favorite': Icons.favorite,
    'favorite_border': Icons.favorite_border,
    'star_outlined': Icons.star_border,
    'location_on': Icons.location_on,
    'access_time': Icons.access_time,
    'restaurant_outlined': Icons.restaurant_outlined,
    'account_balance_wallet': Icons.account_balance_wallet,
    'phone_android': Icons.phone_android,
    'facebook': Icons.facebook,
    'g_mobiledata': Icons.g_mobiledata,
    'person_outline': Icons.person_outline,
    'check_circle_outlined': Icons.check_circle_outline,
    'edit_outlined': Icons.edit_outlined,
    'location_off_outlined': Icons.location_off_outlined,
    'shopping_cart_outlined': Icons.shopping_cart_outlined,
    'keyboard_arrow_down': Icons.keyboard_arrow_down,
    'arrow_forward_ios': Icons.arrow_forward_ios,
    'sms_outlined': Icons.sms_outlined,
    'star_half': Icons.star_half,
    'star_border': Icons.star_border,
    'settings': Icons.settings,
    'help': Icons.help_outline,
    'battery': Icons.battery_std,
    'send': Icons.send,
    'more_horiz': Icons.more_horiz,
    'chevron_right': Icons.chevron_right,
    'arrow_upward': Icons.arrow_upward,
    'shopping_bag': Icons.shopping_bag,
    'card_giftcard': Icons.card_giftcard,
    'trending_up': Icons.trending_up,
    'motorcycle': Icons.two_wheeler,
    'receipt': Icons.receipt_long,
    'filter_list': Icons.filter_list,
  };

  // Icônes Cupertino pour iOS
  static const Map<String, IconData> _cupertinoIcons = {
    'home': CupertinoIcons.home,
    'menu': CupertinoIcons.bars,
    'search': CupertinoIcons.search,
    'add': CupertinoIcons.add,
    'delete': CupertinoIcons.delete,
    'edit': CupertinoIcons.pencil,
    'notifications': CupertinoIcons.bell,
    'profile': CupertinoIcons.profile_circled,
    'logout': CupertinoIcons.square_arrow_left,
    'email': CupertinoIcons.mail,
    'phone': CupertinoIcons.phone,
    'password': CupertinoIcons.lock,
    'visibility_on': CupertinoIcons.eye,
    'visibility_off': CupertinoIcons.eye_slash,
    'check': CupertinoIcons.check_mark_circled,
    'check_outline': CupertinoIcons.check_mark_circled,
    'camera': CupertinoIcons.camera,
    'photo_library': CupertinoIcons.photo,
    'cloud_upload': CupertinoIcons.cloud_upload,
    'upload_file': CupertinoIcons.doc_text,
    'location': CupertinoIcons.location,
    'arrow_forward': CupertinoIcons.arrow_right,
    'arrow_back': CupertinoIcons.back,
    'message': CupertinoIcons.conversation_bubble,
    'download': CupertinoIcons.arrow_down_circle,
    'share': CupertinoIcons.share,
    'refresh': CupertinoIcons.refresh,
    'cart': CupertinoIcons.shopping_cart,
    'restaurant': CupertinoIcons.heart,
    'delivery': CupertinoIcons.cube_box_fill,
    'history': CupertinoIcons.clock,
    'payment': CupertinoIcons.creditcard,
    'info': CupertinoIcons.info,
    'success': CupertinoIcons.checkmark_circle,
    'warning': CupertinoIcons.exclamationmark_triangle,
    'error': CupertinoIcons.exclamationmark_circle,
    'close': CupertinoIcons.xmark,
    'filter': CupertinoIcons.slider_horizontal_3,
    'clock': CupertinoIcons.clock,
    'star': CupertinoIcons.star_fill,
    'home_outlined': CupertinoIcons.home,
    'wallet': CupertinoIcons.creditcard,
    // Icônes supplémentaires utilisées dans l'application
    'delete_outline': CupertinoIcons.trash,
    'remove': CupertinoIcons.minus,
    'notifications_outlined': CupertinoIcons.bell,
    'done_all': CupertinoIcons.checkmark_alt,
    'more_vert': CupertinoIcons.ellipsis_vertical,
    'shopping_bag_outlined': CupertinoIcons.shopping_cart,
    'local_offer_outlined': CupertinoIcons.tag,
    'payment_outlined': CupertinoIcons.creditcard,
    'mark_as_unread': CupertinoIcons.envelope_badge,
    'done': CupertinoIcons.checkmark,
    'favorite': CupertinoIcons.heart_fill,
    'favorite_border': CupertinoIcons.heart,
    'star_outlined': CupertinoIcons.star,
    'location_on': CupertinoIcons.location_solid,
    'access_time': CupertinoIcons.clock,
    'restaurant_outlined': CupertinoIcons.heart,
    'account_balance_wallet': CupertinoIcons.creditcard_fill,
    'phone_android': CupertinoIcons.device_phone_portrait,
    'facebook': CupertinoIcons.globe,
    'g_mobiledata': CupertinoIcons.globe,
    'person_outline': CupertinoIcons.person,
    'check_circle_outlined': CupertinoIcons.checkmark_circle,
    'edit_outlined': CupertinoIcons.pencil,
    'location_off_outlined': CupertinoIcons.location_slash,
    'shopping_cart_outlined': CupertinoIcons.cart,
    'keyboard_arrow_down': CupertinoIcons.chevron_down,
    'arrow_forward_ios': CupertinoIcons.chevron_forward,
    'sms_outlined': CupertinoIcons.chat_bubble,
    'star_half': CupertinoIcons.star_lefthalf_fill,
    'star_border': CupertinoIcons.star,
    'settings': CupertinoIcons.settings,
    'help': CupertinoIcons.question_circle,
    'battery': CupertinoIcons.battery_full,
    'send': CupertinoIcons.paperplane,
    'more_horiz': CupertinoIcons.ellipsis,
    'chevron_right': CupertinoIcons.chevron_right,
    'arrow_upward': CupertinoIcons.arrow_up,
    'shopping_bag': CupertinoIcons.bag,
    'card_giftcard': CupertinoIcons.gift,
    'trending_up': CupertinoIcons.arrow_up_right,
    'motorcycle': CupertinoIcons.cube_box,
    'receipt': CupertinoIcons.list_bullet,
    'filter_list': CupertinoIcons.line_horizontal_3_decrease,
  };

  static Icon getIcon(String iconName, {Color? color, double? size}) {
    final IconData iconData =
    defaultTargetPlatform == TargetPlatform.iOS
        ? _cupertinoIcons[iconName] ?? _materialIcons[iconName]!
        : _materialIcons[iconName] ?? _cupertinoIcons[iconName]!;

    return Icon(iconData, color: color, size: size);
  }

  static IconData getIconData(String iconName) {
    return defaultTargetPlatform == TargetPlatform.iOS
        ? _cupertinoIcons[iconName] ?? _materialIcons[iconName]!
        : _materialIcons[iconName] ?? _cupertinoIcons[iconName]!;
  }
}
